<table>
    <thead>
    <tr>
        <th>firstname</th>
        <th>lastname</th>
        <th>phone</th>
        <th>email</th>
        <th>company</th>
        <th>businessno</th>
        <th>address</th>
        <th>town</th>
        <th>postcode</th>
        <th>state</th>
        <th>country</th>
        <th>notes</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>
